### ISSUE TITLE
What's next ?

### ISSUE THREAD

**Issue by Becheler** [mnavascues/Evaluation_Fc#1]
If I can do/try to do/ something in parallel ... restructuring, debugging, simplifications ?

**Comment by mnavascues** [comment]
Let me some time to get again into the code and I'll get back to you.

On 06/01/15 19:03, Arnaud Becheler wrote:
> If I can do something in parallel ... restructuring, debugging,
> simplifications ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mnavascues/Evaluation_Fc/issues/1>.
>


-- 
Miguel NAVASCUÉS, PhD

Chargé de Recherche (CR2) INRA

UMR CBGP Centre de Biologie pour la Gestion des Populations
755 avenue du campus Agropolis
CS30016
34988 Montferrier-sur-Lez cedex (France)

phone:  +33(0)4.99.62.33.70
fax:    +33(0)4.99.62.33.45
e-mail: miguel.navascues AT supagro.inra.fr
e-mail: m.navascues AT gmail.com
Skype:  m.navascues
web:    http://www1.montpellier.inra.fr/cbgp/
web:    http://sites.google.com/site/navascuesresearch/
